### PR TITLE
bug:userdetail-connection-firebase-database

### LINKED ISSUE #4: [Bug] User details must be stored in Firebase Database.
As the authentication is done by the user, the data of the **user is still not being stored in the Firebase database**.

### PR DESCRIPTION
**Pull request by krishna-nayak**
- Resolves #4 
Establish a connection to the Firebase Database user collection for the fields: **firstName**, **lastName**, **email**, and **city**. Only collect this information as requested on the registration page.

### CODE REVIEW

File: src/pages/Registration.jsx [hunk 1]
```diff
@@ -55,13 +56,19 @@ function Registration() {
...
-        .then((userCredential) => {
+        .then(async (userCredential) => {
           // eslint-disable-next-line no-shadow
           const { user } = userCredential;
           console.log(user);
+          await addDoc(collection(db, "users"), {
+            firstName,
+            lastName,
+            email,
+            city,
```
Comment (ManishaSwain8) [inline src/pages/Registration.jsx:69]: city isn't required, whats the use anyway.. storing extra data

Comment (krishna-nayak) [reply src/pages/Registration.jsx:69]: To prevent false location claims, users should only attend events in their actual place of residence. Otherwise, it can cause issues for other members. If a user cannot attend, it is best for them not to join the event at all.
